name: Confirm pull request trigger

on:
  pull_request:
    branches:
      - develop
      - testing
      - production

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout resource
        uses: actions/checkout@v2

      - name: Show branches
        run: |
          git branch
          echo "source => ${GITHUB_HEAD_REF}"
          echo "target => ${GITHUB_BASE_REF}"
          echo "${{ toJson(github) }}"
